version: 3

images:
  base_image:
    name: swr.lan.aiminjie.com/openeuler/openeuler:24.03

dependencies:
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  system:
    - openssh-clients
    - sshpass
    - git
  python:
    - jq
    - jmespath
    - receptorctl
    - ansible
  galaxy:
    collections:
      - name: kubernetes.core
    roles:
      - src: git+https://github.com/magicJie/ansible-modules-bitwarden

additional_build_files:
  - src: files/bw
    dest: ./
  - src: files/receptor
    dest: ./

additional_build_steps:
  append_base:
    - COPY _build/bw /usr/local/bin/
    - RUN chmod +x /usr/local/bin/bw
    - COPY _build/receptor /usr/local/bin/
    - RUN chmod +x /usr/local/bin/receptor

  prepend_galaxy:
    - RUN dnf install -y git